// Dataset atualizado a partir de pesquisa ao vivo em 31/07/2026.
// Odds de mercado: The Odds API (probabilidades justas via remoção de vig, prioridade Pinnacle).
// Dados de forma/desfalques/H2H: imprensa esportiva brasileira (Lance!, ge, Soccerway, otempo, Beira do Campo, NETVASCO).
const DATASET = {
  updatedAt: "2026-07-31T18:40:00-03:00",

  competitions: [
    {
      id: "copadobrasil",
      nome: "Copa do Brasil",
      status: "ativa",
      statusNota: "Oitavas de final: jogos de ida entre 01 e 03/08 (este fim de semana), volta entre 04 e 06/08. Sem cobertura de odds na The Odds API para esta competição.",
      tabela: null,
      partidas: [
        {
          id: "vas-flu-cdb",
          rodada: "Oitavas — ida",
          casa: "Vasco", fora: "Fluminense",
          kickoff: "2026-08-01T17:30:00-03:00",
          local: "Maracanã, Rio de Janeiro",
          profundidade: "completa",
          mercado: null,
          forma: { casaResumo: "Reedição da semifinal do ano passado, quando o Vasco eliminou o Fluminense.", foraResumo: "Departamento médico ativo no setor defensivo." },
          h2h: "Nos últimos 10 confrontos: 5 vitórias do Fluminense, 4 do Vasco, 1 empate.",
          desfalques: {
            casa: ["Thiago Mendes (suspenso, expulso na fase anterior)"],
            fora: ["GB (departamento médico)", "Mateus Carvalho (departamento médico)", "Jair (retorno gradual de lesão no joelho, quase 1 ano fora)"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Clássico carioca abre as oitavas, no Maracanã — Copa do Brasil não tem cobertura de odds na The Odds API. Retrospecto recente é equilibrado (5V Flu, 4V Vasco, 1E em 10 jogos)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cam-juv-cdb",
          rodada: "Oitavas — ida",
          casa: "Atlético-MG", fora: "Juventude",
          kickoff: "2026-08-01T19:30:00-03:00",
          local: "Arena MRV, Belo Horizonte",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "san-rem-cdb",
          rodada: "Oitavas — ida",
          casa: "Santos", fora: "Remo",
          kickoff: "2026-08-01T21:00:00-03:00",
          local: "Vila Belmiro, Santos",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "pal-for-cdb",
          rodada: "Oitavas — ida",
          casa: "Palmeiras", fora: "Fortaleza",
          kickoff: "2026-08-02T16:00:00-03:00",
          local: "Allianz Parque, São Paulo",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "mir-gre-cdb",
          rodada: "Oitavas — ida",
          casa: "Mirassol", fora: "Grêmio",
          kickoff: "2026-08-02T18:00:00-03:00",
          local: "Maião, Mirassol",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cha-cru-cdb",
          rodada: "Oitavas — ida",
          casa: "Chapecoense", fora: "Cruzeiro",
          kickoff: "2026-08-02T18:30:00-03:00",
          local: "Arena Condá, Chapecó",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "int-cor-cdb",
          rodada: "Oitavas — ida",
          casa: "Internacional", fora: "Corinthians",
          kickoff: "2026-08-02T19:30:00-03:00",
          local: "Beira-Rio, Porto Alegre",
          profundidade: "básica",
          mercado: null,
          forma: { casaResumo: "Chega deste confronto pressionado — na zona de rebaixamento do Brasileirão após a 21ª rodada.", foraResumo: null },
          h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Inter chega pressionado pela situação no Brasileirão (ver seção Brasileirão) — sem cobertura de odds para a Copa do Brasil e sem escalação/desfalques levantados ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cap-vit-cdb",
          rodada: "Oitavas — ida",
          casa: "Athletico-PR", fora: "Vitória",
          kickoff: "2026-08-03T21:00:00-03:00",
          local: "Arena da Baixada, Curitiba",
          profundidade: "básica",
          mercado: null,
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Sem cobertura de odds nem notícias de elenco levantadas para esta partida ainda." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
      ],
    },
    {
      id: "brasileirao",
      nome: "Brasileirão Série A",
      status: "ativa",
      statusNota: "21ª rodada concluída, exceto 4 jogos adiados por causa dos playoffs da Sul-Americana (sem nova data ainda). 22ª rodada começa em 08/08.",
      tabela: [
        { pos: 1, time: "Palmeiras", pts: 47, sg: "+22", tag: "Libertadores" },
        { pos: 2, time: "Flamengo", pts: 39, sg: "+19", tag: "Libertadores" },
        { pos: 3, time: "Athletico-PR", pts: 37, sg: "+9", tag: "Libertadores" },
        { pos: 4, time: "Fluminense", pts: 34, sg: "+5", tag: "Libertadores" },
        { pos: 5, time: "Bahia", pts: 32, sg: "+4", tag: "Libertadores (prelim)" },
        { pos: 6, time: "Bragantino", pts: 31, sg: "+6", tag: "Sul-Americana" },
        { pos: 7, time: "Cruzeiro", pts: 30, sg: "-3", tag: "Sul-Americana" },
        { pos: 8, time: "Corinthians", pts: 29, sg: "+2", tag: "Sul-Americana" },
        { pos: 9, time: "Botafogo", pts: 29, sg: "+2", tag: "Sul-Americana" },
        { pos: 10, time: "Atlético-MG", pts: 28, sg: "0", tag: "Sul-Americana" },
        { pos: 11, time: "Coritiba", pts: 27, sg: "-3", tag: "Sul-Americana" },
        { pos: 12, time: "São Paulo", pts: 26, sg: "+2", tag: "" },
        { pos: 13, time: "Vitória", pts: 26, sg: "-9", tag: "" },
        { pos: 14, time: "Mirassol", pts: 23, sg: "-4", tag: "" },
        { pos: 15, time: "Santos", pts: 22, sg: "-4", tag: "" },
        { pos: 16, time: "Grêmio", pts: 22, sg: "-4", tag: "" },
        { pos: 17, time: "Internacional", pts: 22, sg: "-4", tag: "Rebaixamento" },
        { pos: 18, time: "Vasco da Gama", pts: 21, sg: "-8", tag: "Rebaixamento" },
        { pos: 19, time: "Remo", pts: 21, sg: "-10", tag: "Rebaixamento" },
        { pos: 20, time: "Chapecoense", pts: 10, sg: "-22", tag: "Rebaixamento" },
      ],
      partidas: [
        {
          id: "postponed-note",
          rodada: "21ª rodada — 4 jogos adiados, sem nova data",
          casa: "Botafogo / São Paulo / Atlético-MG / Chapecoense",
          fora: "Grêmio / Santos / Bragantino / Vasco",
          kickoff: null,
          local: null,
          profundidade: "básica",
          mercado: null,
          forma: { casaResumo: "CBF adiou os 4 jogos (Botafogo x Grêmio, São Paulo x Santos, Atlético-MG x Bragantino, Chapecoense x Vasco) porque Grêmio, Santos, Bragantino e Vasco disputavam a volta dos playoffs da Sul-Americana na mesma semana. Novas datas ainda não anunciadas pela CBF.", foraResumo: null },
          h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Aguardando nova data", nota: "Fique de olho — quando a CBF divulgar as novas datas, essas 4 partidas voltam a aparecer aqui com odds e análise completa." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "gre-sao-r22",
          rodada: "22ª rodada",
          casa: "Grêmio", fora: "São Paulo",
          casaPos: 16, foraPos: 12,
          kickoff: "2026-08-08T16:00:00-03:00",
          local: "Arena do Grêmio, Porto Alegre",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.393, empate: 0.296, fora: 0.311 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "22ª rodada começa em 08/08 — jogo equilibrado pelo mercado (39% x 31% x 30% empate)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "rem-cam-r22",
          rodada: "22ª rodada",
          casa: "Remo", fora: "Atlético-MG",
          casaPos: 19, foraPos: 10,
          kickoff: "2026-08-08T18:30:00-03:00",
          local: "Baenão, Belém",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.313, empate: 0.290, fora: 0.396 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Mercado favorece o Atlético-MG fora (39,6%) contra o Remo, que está no Z4 (39,6% x 31,3%)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cor-cha-r22",
          rodada: "22ª rodada",
          casa: "Coritiba", fora: "Chapecoense",
          casaPos: 11, foraPos: 20,
          kickoff: "2026-08-08T20:30:00-03:00",
          local: "Couto Pereira, Curitiba",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.580, empate: 0.240, fora: 0.180 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Coritiba favorito claro (58%) contra a lanterna Chapecoense (18%)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "bot-flu-r22",
          rodada: "22ª rodada",
          casa: "Botafogo", fora: "Fluminense",
          casaPos: 9, foraPos: 4,
          kickoff: "2026-08-08T21:00:00-03:00",
          local: "Nilton Santos, Rio de Janeiro",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.358, empate: 0.315, fora: 0.327 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Clássico carioca dividido pelo mercado (36% x 33% x 32% empate) — 9º x 4º colocado." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cru-mir-r22",
          rodada: "22ª rodada",
          casa: "Cruzeiro", fora: "Mirassol",
          casaPos: 7, foraPos: 14,
          kickoff: "2026-08-09T11:00:00-03:00",
          local: "Mineirão, Belo Horizonte",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.566, empate: 0.249, fora: 0.185 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Cruzeiro favorito claro em casa (57%) contra o Mirassol (19%), que vinha de vitória que o tirou do Z4." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "bah-vas-r22",
          rodada: "22ª rodada",
          casa: "Bahia", fora: "Vasco",
          casaPos: 5, foraPos: 18,
          kickoff: "2026-08-09T16:00:00-03:00",
          local: "Arena Fonte Nova, Salvador",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.501, empate: 0.253, fora: 0.246 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Bahia (vaga na Libertadores) favorito moderado em casa contra o Vasco (Z4): 50% x 25%." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "pal-int-r22",
          rodada: "22ª rodada",
          casa: "Palmeiras", fora: "Internacional",
          casaPos: 1, foraPos: 17,
          kickoff: "2026-08-09T16:00:00-03:00",
          local: "Allianz Parque, São Paulo",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.587, empate: 0.250, fora: 0.163 },
          forma: { casaResumo: null, foraResumo: "Chega desta rodada dentro do Z4 (17º) pela primeira vez na temporada, mesmo após o empate com o Flamengo — ver histórico da 21ª rodada." },
          h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: 4, tag: "Favorito claro (mercado)", nota: "Líder isolado (1º) recebe o Internacional, que caiu no Z4 (17º) — 58,7% de mercado para o Palmeiras. Combinação de melhor time da competição contra time em crise agrava o cenário para o Inter." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "san-cap-r22",
          rodada: "22ª rodada",
          casa: "Santos", fora: "Athletico-PR",
          casaPos: 15, foraPos: 3,
          kickoff: "2026-08-09T18:30:00-03:00",
          local: "Vila Belmiro, Santos",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.435, empate: 0.288, fora: 0.276 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Santos favorito moderado em casa mesmo sendo o time pior colocado (44% x 28%)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "bra-cor-r22",
          rodada: "22ª rodada",
          casa: "Bragantino", fora: "Corinthians",
          casaPos: 6, foraPos: 8,
          kickoff: "2026-08-09T18:30:00-03:00",
          local: "Nabi Abi Chedid, Bragança Paulista",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.448, empate: 0.289, fora: 0.263 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Próxima rodada — odds já publicadas, análise ainda básica", nota: "Confronto direto pela vaga na Sul-Americana (6º x 8º) — Bragantino favorito moderado em casa (45% x 26%)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "fla-vit-r22",
          rodada: "22ª rodada",
          casa: "Flamengo", fora: "Vitória",
          casaPos: 2, foraPos: 13,
          kickoff: "2026-08-09T19:30:00-03:00",
          local: "Maracanã, Rio de Janeiro",
          profundidade: "básica",
          mercado: { fonte: "pinnacle", casa: 0.776, empate: 0.147, fora: 0.078 },
          forma: null, h2h: null, desfalques: null, fadiga: null,
          sinais: {
            resultado: { nivel: 5, tag: "Favorito muito claro (mercado)", nota: "77,6% para o Flamengo em casa — maior favoritismo levantado nesta atualização em qualquer competição." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
      ],
    },
    {
      id: "sulamericana",
      nome: "CONMEBOL Sul-Americana",
      status: "pausada",
      statusNota: "Playoffs concluídos nesta semana. Sem jogos até as oitavas de final, entre 11 e 20/08 (ida 11–13, volta 18–20).",
      tabela: null,
      partidas: [],
    },
    {
      id: "libertadores",
      nome: "CONMEBOL Libertadores",
      status: "pausada",
      statusNota: "Sem jogos esta semana — oitavas de final entre 11 e 20/08 (ida 11–13, volta 18–20).",
      tabela: null,
      partidas: [],
    },
  ],
};
