// Dataset atualizado a partir de pesquisa ao vivo em 28/09/2026.
// Odds de mercado: The Odds API — indisponível nesta atualização (domínio api.the-odds-api.com bloqueado
// pela política de rede do ambiente de execução). Todos os campos "mercado" desta rodada estão null.
// Dados de forma/desfalques/H2H/tabela: imprensa esportiva brasileira (Lance!, ge, Gazeta Esportiva, Soccerway,
// CNN Brasil, o Tempo, Vavel, Terra) via busca na web. Tabela de classificação com saldo de gols confirmado
// apenas para os times em que múltiplas fontes concordaram; demais times aparecem com SG "—" (não confirmado).
const DATASET = {
  updatedAt: "2026-09-28T07:15:00-03:00",

  competitions: [
    {
      id: "copadobrasil",
      nome: "Copa do Brasil",
      status: "pausada",
      statusNota: "Quartas de final terminaram em 02–03/09 (Santos, Palmeiras, Atlético-MG, Vasco, Cruzeiro, Grêmio, Internacional e Vitória classificados). Sem jogos até a semifinal, com ida marcada para 01/11 e volta para 08/11 — intervalo causado pela Super Data Fifa e pelas fases decisivas de Libertadores/Sul-Americana. Sem cobertura de odds na The Odds API para esta competição.",
      tabela: null,
      partidas: [],
    },
    {
      id: "brasileirao",
      nome: "Brasileirão Série A",
      status: "ativa",
      statusNota: "28ª rodada concluída em 19–21/09 (Flamengo abriu 3 pontos de vantagem sobre o Palmeiras). O campeonato está em pausa para a Super Data Fifa, mas 2 jogos atrasados da 21ª rodada (adiados em agosto por causa dos playoffs da Sul-Americana) caem justamente nesta janela de 7 dias: São Paulo x Santos (02/10) e Atlético-MG x Bragantino (03/10). A 29ª rodada volta normalmente em 07–08/10. Odds não puderam ser consultadas nesta atualização (falha de acesso à The Odds API no ambiente de execução) — sinal de resultado por mercado indisponível para os 2 jogos abaixo.",
      tabela: [
        { pos: 1, time: "Flamengo", pts: 60, sg: "+32", tag: "Libertadores" },
        { pos: 2, time: "Palmeiras", pts: 57, sg: "+26", tag: "Libertadores" },
        { pos: 3, time: "Athletico-PR", pts: 49, sg: "+11", tag: "Libertadores" },
        { pos: 4, time: "Fluminense", pts: 48, sg: "+8", tag: "Libertadores" },
        { pos: 5, time: "Bahia", pts: 46, sg: "+8", tag: "Libertadores (prelim)" },
        { pos: 6, time: "Cruzeiro", pts: 45, sg: "—", tag: "Sul-Americana" },
        { pos: 7, time: "Atlético-MG", pts: 40, sg: "—", tag: "Sul-Americana" },
        { pos: 8, time: "Santos", pts: 38, sg: "—", tag: "Sul-Americana" },
        { pos: 9, time: "Coritiba", pts: 38, sg: "—", tag: "Sul-Americana" },
        { pos: 10, time: "Bragantino", pts: 36, sg: "—", tag: "Sul-Americana" },
        { pos: 11, time: "São Paulo", pts: 36, sg: "—", tag: "Sul-Americana" },
        { pos: 12, time: "Botafogo", pts: 35, sg: "—", tag: "" },
        { pos: 13, time: "Vitória", pts: 33, sg: "—", tag: "" },
        { pos: 14, time: "Corinthians", pts: 32, sg: "—", tag: "" },
        { pos: 15, time: "Mirassol", pts: 32, sg: "—", tag: "" },
        { pos: 16, time: "Vasco da Gama", pts: 31, sg: "—", tag: "" },
        { pos: 17, time: "Grêmio", pts: 29, sg: "—", tag: "Rebaixamento" },
        { pos: 18, time: "Internacional", pts: 28, sg: "—", tag: "Rebaixamento" },
        { pos: 19, time: "Remo", pts: 23, sg: "—", tag: "Rebaixamento" },
        { pos: 20, time: "Chapecoense", pts: 18, sg: "-22", tag: "Rebaixamento" },
      ],
      partidas: [
        {
          id: "sao-san-r21-atrasado",
          rodada: "21ª rodada — jogo atrasado",
          casa: "São Paulo", fora: "Santos",
          casaPos: 11, foraPos: 8,
          kickoff: "2026-10-02T20:00:00-03:00",
          local: "Morumbis, São Paulo",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "São Paulo é o 11º colocado (36 pts). Jogo remarcado por causa do confronto do Santos nas oitavas da Copa do Brasil em 01/08.",
            foraResumo: "Santos vem de sequência sem derrota na competição e chega como 8º colocado (38 pts). Por cair na Data Fifa, o time não deve ter desfalques por convocação — poupa o elenco desse risco específico.",
          },
          h2h: "No turno, em Vila Belmiro, São Paulo e Santos empataram em 1 a 1 (Zé Rafael abriu o placar para o Santos, Calleri empatou para o São Paulo).",
          desfalques: null,
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "The Odds API não pôde ser consultada nesta atualização (bloqueio de rede no ambiente de execução) — sem probabilidade de mercado para este clássico. Retrospecto recente é equilibrado: empate 1-1 no turno e Santos sem perder há várias rodadas." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cam-bra-r21-atrasado",
          rodada: "21ª rodada — jogo atrasado",
          casa: "Atlético-MG", fora: "Bragantino",
          casaPos: 7, foraPos: 10,
          kickoff: "2026-10-03T18:30:00-03:00",
          local: "Arena MRV, Belo Horizonte",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Atlético-MG é o 7º colocado (40 pts), na briga pela vaga na Sul-Americana. Desfalques por convocação para a Data Fifa: Kevin Castaño, Alan Franco, Ángelo Preciado e Alan Minda (seleções); Gustavo Scarpa também fora, por lesão.",
            foraResumo: "Bragantino é o 10º colocado (36 pts). Desfalques: José Hurtado (seleção); Tiago Volpi, Patrick e Davi Gomes (departamento médico).",
          },
          h2h: "Retrospecto histórico favorece o Atlético-MG: 7 vitórias do Galo, 2 do Bragantino e 6 empates nos confrontos mais recentes.",
          desfalques: {
            casa: ["Kevin Castaño (seleção)", "Alan Franco (seleção)", "Ángelo Preciado (seleção)", "Alan Minda (seleção)", "Gustavo Scarpa (departamento médico)"],
            fora: ["José Hurtado (seleção)", "Tiago Volpi (departamento médico)", "Patrick (departamento médico)", "Davi Gomes (departamento médico)"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "The Odds API não pôde ser consultada nesta atualização (bloqueio de rede no ambiente de execução). Retrospecto histórico favorece o Atlético-MG (7V x 2V x 6E), mas ambos os times jogam com desfalques relevantes por convocação para a Data Fifa." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
      ],
    },
    {
      id: "sulamericana",
      nome: "CONMEBOL Sul-Americana",
      status: "pausada",
      statusNota: "Quartas de final terminaram em 17/09, com times brasileiros (Atlético-MG, Botafogo, Grêmio, Bragantino, Santos, São Paulo e Vasco no total de 7 representantes ao longo da competição) já definidos ou eliminados nesta fase. Sem jogos nos próximos 7 dias — semifinais só começam em 13–14/10 (ida), com volta em 20–21/10.",
      tabela: null,
      partidas: [],
    },
    {
      id: "libertadores",
      nome: "CONMEBOL Libertadores",
      status: "pausada",
      statusNota: "Sem jogos nos próximos 7 dias. Semifinais 100% brasileiras de um lado da chave: Fluminense x Palmeiras (ida 14/10 no Maracanã, volta 21/10 no NuBank Parque) e Estudiantes x Flamengo (ida 15/10, volta 22/10 no Maracanã). Final marcada para 28/11, em jogo único, no Estádio Centenário, Montevidéu.",
      tabela: null,
      partidas: [],
    },
  ],
};
