// Dataset atualizado a partir de pesquisa ao vivo em 05/10/2026.
// Odds de mercado: The Odds API — indisponível nesta atualização (domínio api.the-odds-api.com bloqueado
// pela política de rede do ambiente de execução, mesma limitação já registrada na atualização anterior).
// Todos os campos "mercado" desta rodada estão null.
// Dados de forma/desfalques/H2H/tabela: imprensa esportiva brasileira (ge, Lance!, Gazeta Esportiva, Terra,
// CNN Brasil, Coluna do Flamengo, Soccerway, sites oficiais dos clubes) via busca na web. Tabela de
// classificação atualizada com os 2 jogos atrasados da 21ª rodada já disputados (São Paulo 1x2 Santos em
// 02/10 e Atlético-MG 1x0 Bragantino em 03/10).
const DATASET = {
  updatedAt: "2026-10-05T07:15:00-03:00",

  competitions: [
    {
      id: "copadobrasil",
      nome: "Copa do Brasil",
      status: "pausada",
      statusNota: "Semifinais definidas: Grêmio x Atlético-MG e Palmeiras x Vasco. Jogos de ida em 01/11 (Palmeiras x Vasco, 16h, Nubank Parque; Grêmio x Atlético-MG, 18h30, Arena do Grêmio) e de volta em 07–08/11 (Atlético-MG x Grêmio em 07/11, 18h, Arena MRV; Vasco x Palmeiras em 08/11, 17h, São Januário). Sem jogos nos próximos 7 dias. Sem cobertura de odds na The Odds API para esta competição.",
      tabela: null,
      partidas: [],
    },
    {
      id: "brasileirao",
      nome: "Brasileirão Série A",
      status: "ativa",
      statusNota: "Os 2 jogos atrasados da 21ª rodada (adiados em agosto por causa dos playoffs da Sul-Americana) já foram disputados: Santos 2x1 São Paulo em 02/10 (2 gols de Gabigol) e Atlético-MG 1x0 Bragantino em 03/10 (gol de Bernard). Falta remarcar só Chapecoense x Vasco — a CBF ainda não confirmou data até o fechamento desta atualização, então Vasco e Chapecoense seguem com um jogo a menos que os demais. A 29ª rodada é a semana corrente: 10 jogos entre quarta (07/10) e quinta (08/10), aproveitando a Data Fifa. Odds de mercado não puderam ser consultadas nesta atualização (bloqueio de rede ao domínio api.the-odds-api.com no ambiente de execução) — sinal de 'Resultado' por mercado indisponível para todos os jogos abaixo.",
      tabela: [
        { pos: 1, time: "Flamengo", pts: 60, sg: "+32", tag: "Libertadores" },
        { pos: 2, time: "Palmeiras", pts: 57, sg: "+26", tag: "Libertadores" },
        { pos: 3, time: "Athletico-PR", pts: 49, sg: "+11", tag: "Libertadores" },
        { pos: 4, time: "Fluminense", pts: 48, sg: "+8", tag: "Libertadores" },
        { pos: 5, time: "Bahia", pts: 46, sg: "+8", tag: "Libertadores (prelim)" },
        { pos: 6, time: "Cruzeiro", pts: 45, sg: "+2", tag: "Sul-Americana" },
        { pos: 7, time: "Atlético-MG", pts: 43, sg: "+5", tag: "Sul-Americana" },
        { pos: 8, time: "Santos", pts: 41, sg: "+2", tag: "Sul-Americana" },
        { pos: 9, time: "Coritiba", pts: 38, sg: "-6", tag: "Sul-Americana" },
        { pos: 10, time: "Bragantino", pts: 36, sg: "+1", tag: "Sul-Americana" },
        { pos: 11, time: "São Paulo", pts: 36, sg: "+1", tag: "Sul-Americana" },
        { pos: 12, time: "Botafogo", pts: 35, sg: "-4", tag: "" },
        { pos: 13, time: "Vitória", pts: 33, sg: "-14", tag: "" },
        { pos: 14, time: "Corinthians", pts: 32, sg: "-3", tag: "" },
        { pos: 15, time: "Mirassol", pts: 32, sg: "-9", tag: "" },
        { pos: 16, time: "Vasco da Gama", pts: 31, sg: "-7", tag: "" },
        { pos: 17, time: "Grêmio", pts: 29, sg: "-8", tag: "Rebaixamento" },
        { pos: 18, time: "Internacional", pts: 28, sg: "-6", tag: "Rebaixamento" },
        { pos: 19, time: "Remo", pts: 23, sg: "-15", tag: "Rebaixamento" },
        { pos: 20, time: "Chapecoense", pts: 18, sg: "-24", tag: "Rebaixamento" },
      ],
      partidas: [
        {
          id: "bra-mir-r29",
          rodada: "29ª rodada",
          casa: "Bragantino", fora: "Mirassol",
          casaPos: 10, foraPos: 15,
          kickoff: "2026-10-07T19:30:00-03:00",
          local: "Bragança Paulista (SP)",
          profundidade: "básica",
          mercado: null,
          forma: {
            casaResumo: "Bragantino é o 10º colocado (36 pts) e vem de derrota por 1 a 0 para o Atlético-MG na rodada atrasada.",
            foraResumo: "Mirassol é o 15º colocado (32 pts), buscando reação fora da zona de rebaixamento.",
          },
          h2h: null,
          desfalques: null,
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "The Odds API não pôde ser consultada nesta atualização (bloqueio de rede no ambiente de execução). Não foram levantados detalhes de desfalques ou retrospecto recente suficientes para uma leitura qualitativa confiável." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "int-coi-r29",
          rodada: "29ª rodada",
          casa: "Internacional", fora: "Corinthians",
          casaPos: 18, foraPos: 14,
          kickoff: "2026-10-07T19:30:00-03:00",
          local: "Beira-Rio, Porto Alegre (RS)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Internacional é o 18º colocado (28 pts), dentro da zona de rebaixamento, com projeções estatísticas apontando cerca de 69% de chance de queda. Desfalques: Victor Gabriel (suspenso por proteção disciplinar); Benjamin Arhin, Calebe, Kayky e Sérgio Rochet (departamento médico).",
            foraResumo: "Corinthians é o 14º colocado (32 pts), com 6 derrotas seguidas no Brasileirão — a chance de queda nas projeções subiu de 14,6% para cerca de 21,4% após a última rodada. Desfalques: Matheus Bidu e Allan (suspensos); Memphis Depay, Kaio César, Gui Negão e Hugo (departamento médico).",
          },
          h2h: null,
          desfalques: {
            casa: ["Victor Gabriel (suspenso)", "Benjamin Arhin (departamento médico)", "Calebe (departamento médico)", "Kayky (departamento médico)", "Sérgio Rochet (departamento médico)"],
            fora: ["Matheus Bidu (suspenso)", "Allan (suspenso)", "Memphis Depay (departamento médico)", "Kaio César (departamento médico)", "Gui Negão (departamento médico)", "Hugo (departamento médico)"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Confronto direto na luta contra o rebaixamento: Internacional é o 18º colocado (~69% de chance estatística de queda) e o Corinthians vem de 6 derrotas seguidas, com a própria chance de queda subindo nas projeções. Pressão grande dos dois lados, mas sem odds de mercado para calibrar a leitura." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: 2, tag: "Jogo de alta tensão", nota: "Seis-pontos direto na zona de rebaixamento, com os dois lados já desfalcados por suspensão por cartões (Victor Gabriel no Inter; Bidu e Allan no Corinthians). Tensão típica desse tipo de jogo tende a elevar a média de cartões, mas não há estatística de cartões por jogo das duas equipes para confirmar isso com mais de 2 fatores concretos." },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "rem-gre-r29",
          rodada: "29ª rodada",
          casa: "Remo", fora: "Grêmio",
          casaPos: 19, foraPos: 17,
          kickoff: "2026-10-07T19:30:00-03:00",
          local: "Mangueirão, Belém (PA)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Remo é o vice-lanterna (19º, 23 pts) e precisa recuperar 8 pontos de diferença para sair do Z4 nos 10 jogos finais da temporada.",
            foraResumo: "Grêmio abre a zona de rebaixamento (17º, 29 pts). Desfalques confirmados: Gustavo Martins e Noriega, suspensos após o 3º cartão amarelo contra o Palmeiras. Outros seis jogadores estão pendurados (um cartão do suspensão): Weverton, Wallace, Diego Caito, Carlos Vinícius, Dodi e Nardoni.",
          },
          h2h: null,
          desfalques: {
            casa: [],
            fora: ["Gustavo Martins (suspenso)", "Noriega (suspenso)"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Confronto direto na zona de rebaixamento: Remo é vice-lanterna e precisa vencer para encurtar a distância até o Z4; Grêmio abre a zona com 29 pts e já perde dois titulares suspensos (Gustavo Martins e Noriega)." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: 2, tag: "Risco de cartões no Grêmio", nota: "Grêmio tem 6 jogadores pendurados (Weverton, Wallace, Diego Caito, Carlos Vinícius, Dodi e Nardoni) — qualquer cartão amarelo nesse grupo gera desfalque na rodada seguinte, o que historicamente deixa times mais cautelosos em disputas de bola." },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "vit-cha-r29",
          rodada: "29ª rodada",
          casa: "Vitória", fora: "Chapecoense",
          casaPos: 13, foraPos: 20,
          kickoff: "2026-10-07T20:00:00-03:00",
          local: "Barradão, Salvador (BA)",
          profundidade: "básica",
          mercado: null,
          forma: {
            casaResumo: "Vitória é o 13º colocado (33 pts), fora da briga direta por rebaixamento mas sem estar matematicamente seguro.",
            foraResumo: "Chapecoense é a lanterna (20º, 18 pts), com a peor campanha do campeonato e maior saldo de gols negativo (-24).",
          },
          h2h: null,
          desfalques: null,
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "The Odds API não pôde ser consultada nesta atualização. Vitória joga em casa contra a lanterna do campeonato, mas não foram levantados desfalques ou retrospecto recente suficientes para qualificar a leitura além da posição na tabela." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "bot-vas-r29",
          rodada: "29ª rodada",
          casa: "Botafogo", fora: "Vasco da Gama",
          casaPos: 12, foraPos: 16,
          kickoff: "2026-10-07T20:30:00-03:00",
          local: "Nilton Santos, Rio de Janeiro (RJ)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Botafogo é o 12º colocado (35 pts). Desfalques confirmados: Matheus Martins, Edenílson, Jordan Barrera e Kaio Pantaleão, fora de combate.",
            foraResumo: "Vasco é o 16º colocado (31 pts, ainda com um jogo a menos pendente contra a Chapecoense). Desfalques: Andrés Gómez, Brenner e Mateus Carvalho.",
          },
          h2h: null,
          desfalques: {
            casa: ["Matheus Martins", "Edenílson", "Jordan Barrera", "Kaio Pantaleão"],
            fora: ["Andrés Gómez", "Brenner", "Mateus Carvalho"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Clássico carioca com o Botafogo um pouco melhor na tabela (12º x 16º) e ambos os times com desfalques relevantes confirmados, mas sem retrospecto direto recente levantado e sem odds de mercado para calibrar a leitura." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "cru-sap-r29",
          rodada: "29ª rodada",
          casa: "Cruzeiro", fora: "São Paulo",
          casaPos: 6, foraPos: 11,
          kickoff: "2026-10-07T21:30:00-03:00",
          local: "Mineirão, Belo Horizonte (MG)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Cruzeiro é o 6º colocado (45 pts), na briga pela vaga de Sul-Americana. Desfalques no departamento médico: Lucas Romero, Gabriel Pec e Luis Sinisterra.",
            foraResumo: "São Paulo é o 11º colocado (36 pts), vem de derrota na rodada atrasada contra o Santos. Lista extensa de desfalques: Wendell, Nicolas Bosshardt, Aurélio Buta, Enzo Díaz, Iago, Luciano, Rafael e Domingos Duarte. Por outro lado, o time ganha o reforço do retorno de Calleri.",
          },
          h2h: null,
          desfalques: {
            casa: ["Lucas Romero (departamento médico)", "Gabriel Pec (departamento médico)", "Luis Sinisterra (departamento médico)"],
            fora: ["Wendell", "Nicolas Bosshardt", "Aurélio Buta", "Enzo Díaz", "Iago", "Luciano", "Rafael", "Domingos Duarte"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Cruzeiro é o 6º colocado e joga em casa contra um São Paulo 11º colocado com lista extensa de desfalques (8 jogadores indisponíveis) — ainda assim, sem odds de mercado para transformar isso em probabilidade." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "san-fla-r29",
          rodada: "29ª rodada",
          casa: "Santos", fora: "Flamengo",
          casaPos: 8, foraPos: 1,
          kickoff: "2026-10-08T19:30:00-03:00",
          local: "Vila Belmiro, Santos (SP)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Santos é o 8º colocado (41 pts) e vive a melhor sequência desde 2019: 5 vitórias seguidas no Brasileirão, embalado pela virada por 2 a 1 sobre o São Paulo com 2 gols de Gabigol na rodada atrasada.",
            foraResumo: "Flamengo lidera o campeonato com 60 pts e tem a melhor campanha como visitante da competição (27 pts em 14 jogos fora). Retornam de suspensão Paquetá, Samuel Lino e Pulgar. Arrascaeta é desfalque confirmado por fratura no punho esquerdo sofrida em amistoso pelo Uruguai (operado em 01/10); Evertton Araújo (lesão muscular grau 3 no adutor) e Ayrton Lucas (lesão muscular na coxa, sofrida contra o Bragantino) seguem no departamento médico.",
          },
          h2h: "Retrospecto geral desde 2004: 45 jogos, 20 vitórias do Flamengo, 12 do Santos e 13 empates (60 gols do Flamengo, 51 do Santos). Nos confrontos recentes o retrospecto é melhor para o Flamengo: 3-1 em 05/04/2026 e 3-2 em 09/11/2025, com Santos vencendo por 1-0 em 17/07/2025. Tendência de jogos movimentados: 5 dos últimos 6 confrontos tiveram 3 ou mais gols, média de 2,63 gols por partida.",
          desfalques: {
            casa: [],
            fora: ["Arrascaeta (fratura no punho, operado)", "Evertton Araújo (lesão muscular grau 3 no adutor)", "Ayrton Lucas (lesão muscular na coxa)"],
          },
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "The Odds API não pôde ser consultada nesta atualização. Flamengo lidera com ampla vantagem na tabela (60 x 41 pts) e tem a melhor campanha fora de casa do campeonato, mas enfrenta o Santos em grande fase (5 vitórias seguidas) e desfalcado do titular Arrascaeta — leitura dividida sem dado de mercado para arbitrar." },
            ambosMarcam: { nivel: 2, tag: "Histórico recente favorece gols dos dois lados", nota: "Nos últimos 6 confrontos diretos, 5 tiveram 3 ou mais gols — média de 2,63 gols por jogo. Somado a isso, Santos está em fase ofensiva (5 vitórias seguidas) e Flamengo mantém média alta de gols marcados na temporada (55 em 28 jogos)." },
            maisDe25: { nivel: 2, tag: "Tendência de jogos movimentados", nota: "Mesma base do sinal anterior: histórico recente de confrontos com 3+ gols e dois ataques em boa fase. Não é garantia — é só o padrão observado nos últimos encontros." },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "atp-cam-r29",
          rodada: "29ª rodada",
          casa: "Athletico-PR", fora: "Atlético-MG",
          casaPos: 3, foraPos: 7,
          kickoff: "2026-10-08T20:00:00-03:00",
          local: "Arena da Baixada, Curitiba (PR)",
          profundidade: "básica",
          mercado: null,
          forma: {
            casaResumo: "Athletico-PR é o 3º colocado (49 pts), na briga pelo G4 direto da Libertadores.",
            foraResumo: "Atlético-MG é o 7º colocado (43 pts), vem de vitória sobre o Bragantino na rodada atrasada e tenta se aproximar do G6 da Sul-Americana. Não foram levantados desfalques confirmados para este jogo específico.",
          },
          h2h: "Retrospecto geral: 16 vitórias do Atlético-MG, 13 do Athletico-PR e 2 empates. No confronto mais recente (05/04/2026), o Atlético-MG venceu por 2 a 1, com gols de Victor Hugo e Gustavo Scarpa; Athletico-PR marcou com Julimar.",
          desfalques: null,
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Retrospecto geral e o confronto mais recente favorecem ligeiramente o Atlético-MG (16V x 13V x 2E, e vitória por 2-1 no encontro de abril/2026), mas o Athletico-PR está melhor posicionado na tabela (3º x 7º) e joga em casa. Sem odds de mercado e sem dados de desfalques/forma recente suficientes para fechar a leitura." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "flu-crb-r29",
          rodada: "29ª rodada",
          casa: "Fluminense", fora: "Coritiba",
          casaPos: 4, foraPos: 9,
          kickoff: "2026-10-08T21:30:00-03:00",
          local: "Maracanã, Rio de Janeiro (RJ)",
          profundidade: "básica",
          mercado: null,
          forma: {
            casaResumo: "Fluminense é o 4º colocado (48 pts), na briga pelo G4 direto da Libertadores.",
            foraResumo: "Coritiba é o 9º colocado (38 pts), na zona de acesso à Sul-Americana.",
          },
          h2h: null,
          desfalques: null,
          fadiga: null,
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Fluminense joga em casa e está 5 posições acima do Coritiba na tabela, mas não foram levantados desfalques nem retrospecto direto recente para qualificar melhor a leitura, e não há odds de mercado disponíveis." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
        {
          id: "pal-bah-r29",
          rodada: "29ª rodada",
          casa: "Palmeiras", fora: "Bahia",
          casaPos: 2, foraPos: 5,
          kickoff: "2026-10-08T21:30:00-03:00",
          local: "Nubank Parque, São Paulo (SP)",
          profundidade: "completa",
          mercado: null,
          forma: {
            casaResumo: "Palmeiras é o 2º colocado (57 pts), mas entra na rodada com 11 jogadores convocados pelas seleções na Data Fifa: Gustavo Gómez, Ramón Sosa e Mauricio (Paraguai); Jhon Arias (Colômbia); Flaco López e Giay (Argentina); Piquerez e Emiliano Martínez (Uruguai); Kauan Lima, Erick Belé e Heittor (Seleção Brasileira Sub-20). Jefté e Paulinho estão machucados.",
            foraResumo: "Bahia é o 5º colocado (46 pts, na vaga de Libertadores pela fase preliminar). Recupera Michel Araújo. Não foram levantados outros desfalques confirmados do Bahia para este jogo.",
          },
          h2h: "Retrospecto geral favorece o Palmeiras: 12 vitórias x 4 do Bahia, com 9 empates. Nos 2 confrontos mais recentes houve alternância: Bahia venceu por 1 a 0 em 28/09/2025, e o Palmeiras respondeu vencendo por 2 a 1 em 05/04/2026.",
          desfalques: {
            casa: ["Gustavo Gómez (seleção — Paraguai)", "Ramón Sosa (seleção — Paraguai)", "Mauricio (seleção — Paraguai)", "Jhon Arias (seleção — Colômbia)", "Flaco López (seleção — Argentina)", "Giay (seleção — Argentina)", "Piquerez (seleção — Uruguai)", "Emiliano Martínez (seleção — Uruguai)", "Kauan Lima (seleção — Brasil Sub-20)", "Erick Belé (seleção — Brasil Sub-20)", "Heittor (seleção — Brasil Sub-20)", "Jefté (lesão)", "Paulinho (lesão)"],
            fora: [],
          },
          fadiga: "Palmeiras terá até 8 jogadores voltando de compromissos pelas seleções principais na Data Fifa (alguns jogando fora do Brasil dois dias antes), o que pode significar desgaste de viagem e pouco tempo de treino coletivo antes do jogo contra o Bahia.",
          sinais: {
            resultado: { nivel: null, tag: "Sem odds disponíveis", nota: "Palmeiras é o 2º colocado e tem retrospecto geral favorável (12V x 4V x 9E), mas entra desfalcado de pelo menos 11 jogadores convocados pelas seleções — risco real de desgaste e escalação alternativa. Sem odds de mercado para pesar os dois fatores." },
            ambosMarcam: { nivel: null, tag: "Dados insuficientes", nota: "" },
            maisDe25: { nivel: null, tag: "Dados insuficientes", nota: "" },
            cartoes: { nivel: null, tag: "Dados insuficientes", nota: "" },
            escanteios: { nivel: null, tag: "Dados insuficientes", nota: "" },
          },
        },
      ],
    },
    {
      id: "sulamericana",
      nome: "CONMEBOL Sul-Americana",
      status: "pausada",
      statusNota: "Semifinais definidas com dois representantes brasileiros: Vasco x Boca Juniors (ida 13/10, 21h30, La Bombonera) e Atlético-MG x Montevideo City Torque (ida 14/10, 19h, Arena MRV). Jogos de volta em 20/10 (Vasco x Boca Juniors, local a confirmar no Brasil) e 21/10 (Montevideo City Torque x Atlético-MG, Estádio Centenário, Montevidéu). Sem jogos nos próximos 7 dias.",
      tabela: null,
      partidas: [],
    },
    {
      id: "libertadores",
      nome: "CONMEBOL Libertadores",
      status: "pausada",
      statusNota: "Sem jogos nos próximos 7 dias. Semifinais 100% brasileiras de um lado da chave: Fluminense x Palmeiras (ida 14/10, 21h30, Maracanã; volta 21/10, 21h30, Nubank Parque) e Flamengo x Estudiantes (ida 15/10, 21h30, na Argentina — estádio a confirmar; volta 22/10, 21h30, Maracanã). Final marcada para 28/11, em jogo único, no Estádio Centenário, Montevidéu.",
      tabela: null,
      partidas: [],
    },
  ],
};
